server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-6
  data:
    mongodb:
      # no user name and password need to be specified for now
      uri: mongodb://172.220.7.76:2020/CPRMA
